# Generated by Django 4.1.7 on 2023-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hist5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
