# Generated by Django 4.1.7 on 2023-04-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0002_mensagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagens',
            new_name='Mensagem',
        ),
    ]
