# Generated by Django 4.1.7 on 2023-04-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0005_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='password',
            new_name='password1',
        ),
    ]
