# Generated by Django 4.1.7 on 2023-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0007_cadastro_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='rua',
            field=models.TextField(default=''),
        ),
    ]
