# Generated by Django 4.1.7 on 2023-04-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0010_cadastro_complemento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
