# Generated by Django 4.1.7 on 2023-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0011_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(default=0)),
                ('username', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=355)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
