# Generated by Django 4.1.7 on 2023-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='endereco',
            field=models.TextField(default='-'),
        ),
    ]
