# Generated by Django 4.1.7 on 2023-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0003_rename_mensagens_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=355)),
                ('texto', models.TextField(max_length=3000)),
            ],
        ),
    ]
