# Generated by Django 4.1.7 on 2023-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0004_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=355)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
