# Generated by Django 4.1.7 on 2023-04-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0009_cadastro_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='complemento',
            field=models.TextField(default='-'),
        ),
    ]
