# Generated by Django 4.1.7 on 2023-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0012_coletor'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.TextField(max_length=300)),
                ('dia', models.IntegerField(default=1)),
                ('mes', models.IntegerField(default=1)),
                ('horario', models.TextField(max_length=10)),
            ],
        ),
    ]
