# Generated by Django 4.1.7 on 2023-05-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0015_rename_bairro_horario_bairro_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='dia',
            new_name='day',
        ),
    ]
