# Generated by Django 4.1.7 on 2023-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0016_rename_dia_horario_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_coletor', models.TextField(max_length=255)),
                ('rua_problema', models.TextField(default='')),
                ('rota_alternativa', models.TextField(default='-')),
            ],
        ),
    ]
