# Generated by Django 4.1.7 on 2023-05-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0017_rotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coment_trabalho', models.TextField(max_length=10000)),
                ('coment_plataforma', models.TextField(max_length=10000)),
            ],
        ),
    ]
