# Generated by Django 4.1.7 on 2023-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0018_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('endereco', models.TextField(default='-')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
