# Generated by Django 4.1.7 on 2023-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moedas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(default=500)),
            ],
        ),
    ]
