# Generated by Django 4.1.7 on 2023-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOCS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=355)),
                ('endereco', models.TextField(default='-')),
                ('texto', models.TextField(max_length=1000)),
            ],
        ),
    ]
